local STRINGS = GLOBAL.STRINGS


-- Foods
STRINGS.NAMES.JAJANGMON_HW_JAM = "手指果酱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_JAM = "这是哪位的手?"


STRINGS.NAMES.JAJANGMON_HW_COOKIES = "幽灵饼干"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_COOKIES = "呜噢噢噢哦哦"


STRINGS.NAMES.JAJANGMON_HW_DUMPLING = "幽灵水饺"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_DUMPLING = "喔噢噢噢哦哦"


STRINGS.NAMES.JAJANGMON_HW_PUMPKINPIE = "南瓜派"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_PUMPKINPIE = "等等...你在嘲笑我？"


STRINGS.NAMES.JAJANGMON_HW_PUNCH = "水果拼盘"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_PUNCH ="我可以品尝一下不?"

STRINGS.NAMES.JAJANGMON_HW_MUFFIN = "红鹅绒玛芬蛋糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_MUFFIN = "鲜血之红"


STRINGS.NAMES.JAJANGMON_HW_TAFFY = "万圣糖果"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_TAFFY = "甜呐!"


STRINGS.NAMES.JAJANGMON_HW_BACONEGG = "阳光长高高"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_BACONEGG = "呃啊啊啊!"


STRINGS.NAMES.JAJANGMON_HW_MEATBALLS = "眼球意面"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_MEATBALLS = "这些眼球是真的?"


STRINGS.NAMES.JAJANGMON_HW_POWCAKE = "可疑得很玉米汤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_POWCAKE = "安全咩?"


STRINGS.NAMES.JAJANGMON_HW_TURKEY = "万圣火鸡大餐"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_TURKEY = "酷的很呐~"


STRINGS.NAMES.JAJANGMON_HW_WAFFLE = "万圣蛋糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_WAFFLE = "这奶油就像小幽灵一样"


STRINGS.NAMES.JAJANGMON_HW_MELON = "血腥玛丽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_MELON = "如血一般鲜红"


STRINGS.NAMES.JAJANGMON_HW_FISHTACO = "毛骨悚然鱼卷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_FISHTACO = "这真是鱼吗?"


STRINGS.NAMES.JAJANGMON_HW_GUACAMOLE = "万圣鳄梨酱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_GUACAMOLE = "那是鼹鼠鼻子?"


STRINGS.NAMES.JAJANGMON_HW_FISHSTICK = "手指条"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_FISHSTICK = "这些谁的手指呀?"


STRINGS.NAMES.JAJANGMON_HW_ICECREAM = "红玛冰淇淋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_HW_ICECREAM = "好耶!"



--Crops
STRINGS.NAMES.HTF_BLACKMUSHROOM = "黑菇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_BLACKMUSHROOM = "看起来很无理的蘑菇（笑）."

STRINGS.NAMES.HTF_BLACKMUSHROOM_COOKED = "烹饪黑菇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_BLACKMUSHROOM_COOKED = "尝起来好多了."

STRINGS.NAMES.HTF_BLACKMUSHROOM_SEEDS = "蓬松毛毛种"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_BLACKMUSHROOM_SEEDS = "没错是种子."



STRINGS.NAMES.HTF_EYEROSE = "眼玫瑰"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_EYEROSE = "看起来是巨鹿的花."

STRINGS.NAMES.HTF_EYEROSE_COOKED = "烹饪过的眼玫瑰"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_EYEROSE_COOKED = "这下尝起来好多了."

STRINGS.NAMES.HTF_EYEROSE_SEEDS = "玫瑰状种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_EYEROSE_SEEDS = "就是种子."



--Farming
STRINGS.NAMES.KNOWN_HTF_BLACKMUSHROOM_SEEDS = "黑菇种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_HTF_BLACKMUSHROOM_SEEDS = "还是种子."

STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.HTF_BLACKMUSHROOM = "最好别生食 -W"

STRINGS.NAMES.FARM_PLANT_HTF_BLACKMUSHROOM = "黑菇植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_HTF_BLACKMUSHROOM = "有毒咩?"

STRINGS.NAMES.HTF_BLACKMUSHROOM_OVERSIZED = "巨大黑菇植株"
STRINGS.NAMES.HTF_BLACKMUSHROOM_OVERSIZED_WAXED = "打蜡的巨大黑菇植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_BLACKMUSHROOM_OVERSIZED = "超~大~的蘑菇."

STRINGS.NAMES.HTF_BLACKMUSHROOM_OVERSIZED_ROTTEN = "腐烂巨大黑菇植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_BLACKMUSHROOM_OVERSIZED_ROTTEN = "烂菇."



STRINGS.NAMES.KNOWN_HTF_EYEROSE_SEEDS = "眼玫瑰种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_HTF_EYEROSE_SEEDS = "就是种子."

STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.HTF_EYEROSE = "小心别被刺到了。其实眼睛比刺还可怕。 -W"

STRINGS.NAMES.FARM_PLANT_HTF_EYEROSE = "眼玫瑰植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_HTF_EYEROSE = "那些小家伙刚刚是不是眨了眨?"

STRINGS.NAMES.HTF_EYEROSE_OVERSIZED = "巨大眼玫瑰"
STRINGS.NAMES.HTF_EYEROSE_OVERSIZED_WAXED = "打蜡的巨大眼玫瑰"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_EYEROSE_OVERSIZED = "看起来像是巨鹿们的花."

STRINGS.NAMES.HTF_EYEROSE_OVERSIZED_ROTTEN = "腐烂巨大眼玫瑰"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HTF_EYEROSE_OVERSIZED_ROTTEN = "烂掉了啦."


--Items
GLOBAL.STRINGS.RECIPE_DESC.WALL_PUMPKIN_ITEM = "南瓜造墙~."
STRINGS.NAMES.WALL_PUMPKIN = "南瓜墙."
STRINGS.NAMES.WALL_PUMPKIN_ITEM = "南瓜墙."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_PUMPKIN = "是南瓜墙捏."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_PUMPKIN_ITEM = "是南瓜墙捏."