STRINGS.UI.CRAFTING_FILTERS.HYDRATION = "Hydration"

STRINGS.UI.COOKBOOK.FOOD_EFFECTS_DETOX = "缓解宿醉"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_MULLED = "大大缓解宿醉"

STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CAFFINE = "移动速度增加"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_COLA = "最好的饮料"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_COLAQUANTUM = "每个人的最爱"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_INTOXICATION = "微醺盔甲"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_INTOXICATION_GLOW = "微醺的盔甲"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SUS = "值得怀疑的"

STRINGS.ACTIONS.MILK = "牛奶"
STRINGS.ACTIONS.BOIL = "沸腾的"
STRINGS.ACTIONS.DRINK = "喝的"
STRINGS.ACTIONS.GIVEWATER = "把水放进去"
STRINGS.ACTIONS.DRAIN = "喝光"
STRINGS.ACTIONS.PURIFY = "精炼"
STRINGS.ACTIONS.MILKINGTOOL = "牛奶"
STRINGS.ACTIONS.FERMENT = "发酵"

-- well drilling
STRINGS.NAMES.WELL_DRILLING ="钻井机"
STRINGS.NAMES.WELL_DRILLING_ITEM = "钻井钻机"
STRINGS.RECIPE_DESC.WELL_DRILLING_ITEM = "在地上挖个大洞."

-- wells & hole & sprinker
STRINGS.NAMES.HOLE = "洞"
STRINGS.NAMES.WELL = "井"
STRINGS.NAMES.WELL_SPRINKLER = "喷洒器"

STRINGS.NAMES.WELL_KIT = "井套件"
STRINGS.RECIPE_DESC.WELL_KIT = "这里是井一切都很好."
STRINGS.NAMES.WELL_SPRINKLER_KIT = "喷洒器套件"
STRINGS.RECIPE_DESC.WELL_SPRINKLER_KIT = "终极灌溉."

-- desalinator
STRINGS.NAMES.DESALINATOR = "海水淡化器"
STRINGS.RECIPE_DESC.DESALINATOR = "把海水的咸味过滤起来."

-- barrel
STRINGS.NAMES.BARREL = "桶"
STRINGS.RECIPE_DESC.BARREL = "猴子不包括在内."

-- brewery
STRINGS.NAMES.BREWERY = "啤酒厂"
STRINGS.RECIPE_DESC.BREWERY = "大概改善您的饮酒体验."

-- buckets
STRINGS.NAMES.BUCKET_EMPTY = "桶"
STRINGS.RECIPE_DESC.BUCKET_EMPTY = "一个空桶"

-- campkettle
STRINGS.NAMES.CAMPKETTLE_ITEM = "营地水壶套件"
STRINGS.RECIPE_DESC.CAMPKETTLE_ITEM = "你的第一个水壶."
STRINGS.NAMES.CAMPKETTLE = "营地水壶"

-- kettle
STRINGS.NAMES.KETTLE	= "水壶"
STRINGS.RECIPE_DESC.KETTLE = "喝茶时间到啦"

-- portablekettle
STRINGS.NAMES.PORTABLEKETTLE_ITEM	= "便携式水壶"
STRINGS.NAMES.PORTABLEKETTLE = "便携式水壶"
STRINGS.RECIPE_DESC.PORTABLEKETTLE_ITEM = "随时随地煮茶."

-- tea_trees
STRINGS.NAMES.TEA_TREE = "茶树"
STRINGS.NAMES.DUG_TEA_TREE = "茶树"
STRINGS.NAMES.TEA_SEED = "茶树种子"
STRINGS.NAMES.TEA_SEED_COOKED = "烤茶树种子"
STRINGS.NAMES.TEA_SEED_SAPLING = "茶树苗"
STRINGS.NAMES.TEALEAVES = "茶叶"
STRINGS.NAMES.TEALEAVES_DRIED = "干茶叶"

-- caffeinberry
STRINGS.NAMES.DUG_CAFFEINBERRY = "咖啡树"
STRINGS.NAMES.CAFFEINBERRY = "咖啡树"
STRINGS.NAMES.CAFFEINBERRY_BEAN = "咖啡豆"
STRINGS.NAMES.CAFFEINBERRY_BEAN_COOKED = "烤咖啡豆"
STRINGS.NAMES.SPICE_CAFFEINPEPPER = "胡椒碎"
STRINGS.RECIPE_DESC.SPICE_CAFFEINPEPPER = "充满活力的生活调味品."
STRINGS.NAMES.SPICE_CAFFEINPEPPER_FOOD = "胡椒{食物}"

-- preparedrink

STRINGS.NAMES.WATER_CLEAN_ICE = "冰水"
STRINGS.NAMES.WATER_DIRTY_ICE = "脏冰水"
STRINGS.NAMES.WATER_CLEAN = "水"
STRINGS.NAMES.WATER_DIRTY = "脏水"
STRINGS.NAMES.WATER_SALTY = "咸海水"
STRINGS.NAMES.GOOPYDRINK = "水状粘液"
STRINGS.NAMES.FRUITJUICE = "果味混合"
STRINGS.NAMES.BERRIES_JUICE = "浆果汁"
STRINGS.NAMES.POMEGRANATE_JUICE = "石榴汁"
STRINGS.NAMES.BANANA_JUICE = "香蕉汁"
STRINGS.NAMES.FIG_JUICE = "无花果汁"
STRINGS.NAMES.DRAGONJUICE = "龙饮"
STRINGS.NAMES.GLOWBERRYJUICE = "发光浆果汁"
STRINGS.NAMES.CAFFEINBERRY_JUICE = "咖啡"
STRINGS.NAMES.VEGGIE_TEA = "健康蔬菜汁"
STRINGS.NAMES.CARROT_TEA = "胡萝卜茶"
STRINGS.NAMES.CACTUS_TEA = "仙人掌茶"
STRINGS.NAMES.TOMATO_JUICE = "圣母玛利亚(番茄汁)"
STRINGS.NAMES.MULLED = "热饮"
STRINGS.NAMES.GREENTEA = "绿茶"
STRINGS.NAMES.BLACKTEA = "黑茶"
STRINGS.NAMES.BLACKTEA_ICED = "冰茶"
STRINGS.NAMES.FUER = "福尔茶"
STRINGS.NAMES.MIXFLOWER = "混合花茶"
STRINGS.NAMES.HIBISCUSTEA = "芙蓉茶"
STRINGS.NAMES.CACTUSFLOWER_TEA = "仙人掌花茶"
STRINGS.NAMES.LOTUSTEA = "荷花茶"
STRINGS.NAMES.SUSHIBISCUS = "木槿茶"

-- 유령차 유채이탈 관련 코드
STRINGS.NAMES.GHOSTLY_TEA = "幽灵茶"

-- prepareagedrink

STRINGS.NAMES.SPOILED_DRINK = "腐味饮料"
STRINGS.NAMES.SODA = "苏打水"
STRINGS.NAMES.FRUITSODA = "水果苏打水"
STRINGS.NAMES.LEMONLIMESODA = "起泡蜂蜜水"
STRINGS.NAMES.COLA = "可乐"
STRINGS.NAMES.COLAQUANTUM = "能量可乐"
STRINGS.NAMES.CORN_BEER = "玉米啤酒"
STRINGS.NAMES.MADHU = "蜂蜜酒"
STRINGS.NAMES.WINE = "酒"
STRINGS.NAMES.NOBLEWINE = "贵族酒"
STRINGS.NAMES.SPARKLINGWINE = "气泡酒"
STRINGS.NAMES.GLOWBERRYWINE = "发光浆果酒"
STRINGS.NAMES.KUMIS = "电奶酒"