-- Common Dependencies.
local _G 			= GLOBAL
local require 		= _G.require
local STRINGS		= _G.STRINGS


-- The character select screen lines
STRINGS.CHARACTER_TITLES.lambofthecult = "最后的小羊羔"
STRINGS.CHARACTER_NAMES.lambofthecult = "咩咩教主"
STRINGS.CHARACTER_DESCRIPTIONS.lambofthecult = "*戴着拥有巨大力量的红色圣冠.\n*将强大的敌人教化为信徒."
STRINGS.CHARACTER_QUOTES.lambofthecult = "\"领导教内众人的伟大小羊羔. -N\""
STRINGS.CHARACTER_SURVIVABILITY.lambofthecult = "迷途羔羊"

STRINGS.ACTIONS.CROWN_CHANGE = "切换模式"
STRINGS.ACTIONS.CROWNMODE = "诅咒射击"
STRINGS.ACTIONS.CROWNMODE2 = "切换至对应工具"
STRINGS.ACTIONS.CULTPRAYER = "食用信仰"
STRINGS.ACTIONS.TAROTSET = "制作塔罗牌"
STRINGS.ACTIONS.GOLDENLAMBSTATUE = "祷告"
STRINGS.ACTIONS.SHAMURA_USE = "开启/关闭自动拾取"
STRINGS.ACTIONS.DEVOTEE_COMEON = "跟随/停留"

GLOBAL.STRINGS.NAMES.LAMBCROWN = "咩咩圣冠"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN = "Wow"
GLOBAL.STRINGS.RECIPE_DESC.LAMBCROWN = "Reset"


GLOBAL.STRINGS.NAMES.CROWN_F = "The Crown"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROWN_F = "Wow"

GLOBAL.STRINGS.NAMES.LAMBCROWN_ARMS_KNIFE = "咩咩刀"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN_ARMS_KNIFE = "Wow"

GLOBAL.STRINGS.NAMES.LAMBCROWN_ARMS_AXE = "咩咩斧"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN_ARMS_AXE = "Wow"

GLOBAL.STRINGS.NAMES.LAMBCROWN_ARMS_BUGNET = "咩咩捕虫网"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN_ARMS_BUGNET = "Wow"

GLOBAL.STRINGS.NAMES.LAMBCROWN_ARMS_FISHINGROD = "咩咩钓竿"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN_ARMS_FISHINGROD = "Wow"

GLOBAL.STRINGS.NAMES.LAMBCROWN_ARMS_HAMMER = "咩咩锤"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN_ARMS_HAMMER = "Wow"

GLOBAL.STRINGS.NAMES.LAMBCROWN_ARMS_PICAXE = "咩咩镐"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN_ARMS_PICAXE = "Wow"

GLOBAL.STRINGS.NAMES.LAMBCROWN_ARMS_SHOVEL = "咩咩铲"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBCROWN_ARMS_SHOVEL = "Wow"

GLOBAL.STRINGS.NAMES.POOPFOOD_CL = "便便大餐"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POOPFOOD_CL = "Wow"
GLOBAL.STRINGS.RECIPE_DESC.POOPFOOD_CL = "矮油~真恶心~"

GLOBAL.STRINGS.NAMES.LAMBDOLL = "咩咩玩偶"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBDOLL = "It's soooo cute!"
GLOBAL.STRINGS.RECIPE_DESC.LAMBDOLL = "一个可爱的咩咩玩偶"

GLOBAL.STRINGS.NAMES.LAMBTENT = "教会帐篷"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAMBTENT = "Comfortable!"
GLOBAL.STRINGS.RECIPE_DESC.LAMBTENT = "可以睡觉."

GLOBAL.STRINGS.NAMES.DELIEVERROBE = "信徒斗篷"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DELIEVERROBE = "Comfortable!"
GLOBAL.STRINGS.RECIPE_DESC.DELIEVERROBE = "信仰的体现."

GLOBAL.STRINGS.NAMES.GOLDENLAMBSTATUE = "黄金咩咩雕像"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDENLAMBSTATUE = "Comfortable!"
GLOBAL.STRINGS.RECIPE_DESC.GOLDENLAMBSTATUE = "收集信仰之力"

GLOBAL.STRINGS.NAMES.CULTPRAYER = "信仰之力"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTPRAYER = "Comfortable!"
GLOBAL.STRINGS.RECIPE_DESC.CULTPRAYER = "信仰之力！"

GLOBAL.STRINGS.NAMES.TAROTSET = "塔罗牌桌"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAROTSET = "Comfortable!"
GLOBAL.STRINGS.RECIPE_DESC.TAROTSET = "制作塔罗牌"

GLOBAL.STRINGS.NAMES.TAROTCARD_LESHY = "塔罗牌：莱蟋\n 效果：每5s回复20点san值和5点血量"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAROTCARD_LESHY = "Comfortable!"

GLOBAL.STRINGS.NAMES.TAROTCARD_HEKET = "塔罗牌：赫凯特\n 效果：角色攻击力翻倍"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAROTCARD_HEKET = "Comfortable!"

GLOBAL.STRINGS.NAMES.TAROTCARD_KALLAMAR = "塔罗牌：凯拉玛\n 效果：不受过冷过热及潮湿影响，提供光照与50%移速加成"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAROTCARD_KALLAMAR = "Comfortable!"

GLOBAL.STRINGS.NAMES.TAROTCARD_SHAMURA = "塔罗牌：沙穆拉\n 效果：自动拾取小范围内的掉落物并召唤一只帮忙打架的小恶魔"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAROTCARD_SHAMURA = "Comfortable!"

GLOBAL.STRINGS.NAMES.TAROTCARD_NARINDER = "塔罗牌：待终冠主\n 效果：时间无限，可交给队友。死亡后消耗卡牌并复活，抽到此牌后可立刻重抽一张牌"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAROTCARD_NARINDER = "Comfortable!"

GLOBAL.STRINGS.NAMES.SHAMURA_DEVIL = "小恶魔"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHAMURA_DEVIL = "一个值得信赖的小恶魔？"

GLOBAL.STRINGS.NAMES.DEVOTEE = "咩咩信徒"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEVOTEE = "咩咩信徒."

GLOBAL.STRINGS.NAMES.CULTIST_HEADACC_HEKET = "信徒娃娃：赫凯特"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTIST_HEADACC_HEKET = "真的~~超~~级~~可~~爱~~!"
GLOBAL.STRINGS.RECIPE_DESC.CULTIST_HEADACC_HEKET = "时装物品（并不完全是装饰品）"

GLOBAL.STRINGS.NAMES.CULTIST_HEADACC_CROW = "信徒娃娃：乌鸦"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTIST_HEADACC_CROW = "真的~~超~~级~~可~~爱~~!"
GLOBAL.STRINGS.RECIPE_DESC.CULTIST_HEADACC_CROW = "时装物品（并不完全是装饰品）"


GLOBAL.STRINGS.NAMES.CULTIST_HEADACC_KALLAMAR = "信徒娃娃：凯拉玛"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTIST_HEADACC_KALLAMAR = "真的~~超~~级~~可~~爱~~!"
GLOBAL.STRINGS.RECIPE_DESC.CULTIST_HEADACC_KALLAMAR = "时装物品（并不完全是装饰品）"

GLOBAL.STRINGS.NAMES.CULTIST_HEADACC_LESHY = "信徒娃娃：莱蟋"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTIST_HEADACC_LESHY = "真的~~超~~级~~可~~爱~~!"
GLOBAL.STRINGS.RECIPE_DESC.CULTIST_HEADACC_LESHY = "时装物品（并不完全是装饰品）"

GLOBAL.STRINGS.NAMES.CULTIST_HEADACC_NARINDER = "信徒娃娃：待终冠主"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTIST_HEADACC_NARINDER = "真的~~超~~级~~可~~爱~~!"
GLOBAL.STRINGS.RECIPE_DESC.CULTIST_HEADACC_NARINDER = "时装物品（并不完全是装饰品）"


GLOBAL.STRINGS.NAMES.CULTIST_HEADACC_RABBIT = "信徒娃娃：兔子"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTIST_HEADACC_RABBIT = "真的~~超~~级~~可~~爱~~!"
GLOBAL.STRINGS.RECIPE_DESC.CULTIST_HEADACC_RABBIT = "时装物品（并不完全是装饰品）"

GLOBAL.STRINGS.NAMES.CULTIST_HEADACC_SHAMURA = "信徒娃娃：沙穆拉"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CULTIST_HEADACC_SHAMURA = "真的~~超~~级~~可~~爱~~!"
GLOBAL.STRINGS.RECIPE_DESC.CULTIST_HEADACC_SHAMURA = "时装物品（并不完全是装饰品）"

-- Custom speech strings
-- STRINGS.CHARACTERS.LAMBOFTHECULT = require "speech_lambofthecult"

-- The character's name as appears in-game
STRINGS.NAMES.LAMBOFTHECULT = "The Lamb"
STRINGS.SKIN_NAMES.lambofthecult_none = "The Lamb"
