local STRINGS = GLOBAL.STRINGS


-- Foods
STRINGS.NAMES.VTF_CHOCOLATE = "巧克力"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VTF_CHOCOLATE = "这是美味的巧乐力!!"


STRINGS.NAMES.JAJANGMON_VL_CAKE = "迷你巧克力蛋糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_CAKE = "像你的微笑一样甜"


STRINGS.NAMES.JAJANGMON_VL_MEATBALL = "巧克力酱派"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_MEATBALL = "我会把我的真心交给你"


STRINGS.NAMES.JAJANGMON_VL_POWCAKE = "巧克力马卡龙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_POWCAKE = "看起来很美味!"


STRINGS.NAMES.JAJANGMON_VL_PIEROGI = "白巧克力"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_PIEROGI = "好耶!"


STRINGS.NAMES.JAJANGMON_VL_ICECREAM = "爱心冰激凌"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_ICECREAM = " 好耶!"


STRINGS.NAMES.JAJANGMON_VL_FROG = "丘比特蛙腿饭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_FROG = "emmmm...看起来不错"


STRINGS.NAMES.JAJANGMON_VL_TAFFY = "爱心棉花糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_TAFFY = "软软的心"


STRINGS.NAMES.JAJANGMON_VL_COOKIE = "爱心饼干"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_COOKIE = "爽脆的!"


STRINGS.NAMES.JAJANGMON_VL_HONEYHAM = "浪漫牛排"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_HONEYHAM = "超甜的!"


STRINGS.NAMES.JAJANGMON_VL_CHICKEN = "浪漫鸡块"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_CHICKEN = "这是美味的鸡块"


STRINGS.NAMES.JAJANGMON_VL_MEATSTEW = "巧克力奶酪火锅"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_MEATSTEW = "这是炖肉"


STRINGS.NAMES.JAJANGMON_VL_HONEYNUGGET = "浪漫金砖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAJANGMON_VL_HONEYNUGGET = "这是蜂蜜金砖"


-- Items
STRINGS.NAMES.WALL_VL = "浪漫主题墙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_VL = "这是玫瑰主题墙体."


STRINGS.NAMES.WALL_VL_ITEM = "浪漫主题墙"
STRINGS.RECIPE_DESC.WALL_VL_ITEM = "做一个拥有玫瑰气味的墙体"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_VL_ITEM = "超好看的"


STRINGS.NAMES.VL_STATUES = "爱神雕塑(左)"
STRINGS.RECIPE_DESC.VL_STATUES = "爱神雕塑(左)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VL_STATUES = "这就是爱吗?"


STRINGS.NAMES.VL_STATUES_2 = "爱神雕塑(右)"
STRINGS.RECIPE_DESC.VL_STATUES_2 = "爱神雕塑(右)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VL_STATUES_2 = "这就是爱吗?"


STRINGS.NAMES.ROMANTICFLOWER = "花束"
STRINGS.RECIPE_DESC.ROMANTICFLOWER = "给我的宝贝的" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROMANTICFLOWER = "超爱你的呦～"


