--------- 鞭尸怪物修复 理论上也能防止玩家被鞭尸
--AddComponentPostInit("health", function(self)
--    local flag = 0
--    local Old_SetVal = self.SetVal
--    self.SetVal = function(self, val, cause, afflicter, ...)
--        if self.currenthealth <= 0 then
--            flag = flag + 1
--        end
--
--        if Old_SetVal and flag < 2 then
--            Old_SetVal(self, val, cause, afflicter, ...)
--        else
--            Old_SetVal(self, 0, cause, afflicter, ...)
--        end
--    end
--
--end)
