additional_tags_to_fix = {  --修复标签溢出的问题，感谢风铃的api
    -- 'compassbearer',
    -- 'maprevealer',
    -- 'masterchef',
    -- 'professionalchef',
    'nilxin',
    'hulifox',
    'reader',
    'no_myth_flyskill',
    'bookbuilder',
    "swampwhisperer", -- 未知标签 但是不会吓跑颤栗花
    'quagmire_fasthands',
    --伊蕾娜的
    -- 'elena',
    'star_brooch',
    'moon_brooch',
    'a_brooch',
    'ac_brooch',
    'brooch7',
    'brooch12',
    'brooch14a',
    "beefalo", -- 皮弗娄牛
    "hound", -- 猎犬
    "bule_fairyskirt",--冰裙子
    'magicdelta',
    'elaina_healthdelta',
    'black_magic_ysth',
    'magic_wand',
    'magic_wand_cj',
    'brooch19',

    'woodcutter',
    'werehuman',
    -- 'plantkin',--植物人种地
    'healonfertilize',
    'self_fertilizable',
    'pyromaniac',
    'bernieowner',
    'heatresistant',
    'achivbookbuilder',
    'achiveking',
    'fastbuilder',
    'handyperson',
    'achive_science',
    'achiv_shadow',
    'shadowlure',
    'merm_builder',
    'stronggrip',
    'mermfluent',
    'merm',
    'mermguard',
    'fastpicker',
    'fastharvester',
    'expertchef',
    'pebblemaker',
    'pinetreepioneer',
    'slingshot_sharpshooter',
    'efficient_sleeper',
    'dogrider',
    'valkyrie',
    'spiderwhisperer',
    UPGRADETYPES.SPIDER.."_upgradeuser",  --升级蜘蛛巢tag
    'achiv_clockmaker',
    'clockmaker',
    -- 'pocketwatchcaster',-- 旺达警告表
    'wolfgang_no_sg',
    'mightiness_mighty',
    'ghostlyfriend',  --制作阿比盖尔
    'elixirbrewer',
    'achive_elixirbrewer',
    'alwaysblock',

    -- '没有制作减半',
    'has_build_half',

    'huahousrecipe',--小房子
}
-- additional_tags_to_fix = {	--修复标签溢出的问题，感谢风铃的api
--     -- 'compassbearer',
--     -- 'maprevealer',
--     'expertchef',
--     -- 'masterchef',
--     -- 'professionalchef',
--     'stronggrip',
--     'nilxin',
--     'hulifox',
--     'reader',
--     'no_myth_flyskill',
--     'pocketwatchcaster',
--     'clockmaker',
--     'bookbuilder',
--     "swampwhisperer", -- 未知标签 但是不会吓跑颤栗花
--     'quagmire_fasthands',
--     --伊蕾娜的
--     -- 'elena',
--     'star_brooch',
--     'moon_brooch',
--     'a_brooch',
--     'ac_brooch',
--     'brooch7',
--     'brooch12',
--     'brooch14a',
--     "beefalo", -- 皮弗娄牛
--     "hound", -- 猎犬
--     "bule_fairyskirt",--冰裙子
--     'magicdelta',
--     'elaina_healthdelta',
--     'black_magic_ysth',
--     'magic_wand',
--     'magic_wand_cj',
--     'brooch19',

--     'woodcutter',
--     'werehuman',
--     'plantkin',
--     'healonfertilize',
--     'self_fertilizable',
--     'pyromaniac',
--     'bernieowner',
--     'heatresistant',
--     'achivbookbuilder',
--     'achiveking',
--     'fastbuilder',
--     'handyperson',
--     'achive_science',
--     'achiv_shadow',
--     'shadowlure',
--     'merm_builder',
--     'stronggrip',
--     'mermfluent',
--     'merm',
--     'mermguard',
--     'fastpicker',
--     'fastharvester',
--     'expertchef',
--     'pebblemaker',
--     'pinetreepioneer',
--     'slingshot_sharpshooter',
--     'efficient_sleeper',
--     'dogrider',
--     'valkyrie',
--     'spiderwhisperer',
--     UPGRADETYPES.SPIDER.."_upgradeuser",  --升级蜘蛛巢tag
--     'achiv_clockmaker',
--     'clockmaker',
--     'pocketwatchcaster',
--     'wolfgang_no_sg',
--     'mightiness_mighty',
--     'ghostlyfriend',  --制作阿比盖尔
--     'elixirbrewer',
--     'achive_elixirbrewer',
--     'alwaysblock',

--     -- '没有制作减半',
--     'has_build_half',

--     'huahousrecipe',--小房子
-- }